[package]
name = "slashook"
description = "A webhook-based Discord slash command library"
keywords = ["discord", "webhook", "slash-commands"]
categories = ["api-bindings"]
version = "0.1.0"
edition = "2021"
authors = ["Tonkku"]
repository = "https://github.com/tonkku107/slashook"
license = "MIT OR Apache-2.0"

[dependencies]
slashook-macros = { version = "0.1.0", path = "./macros" }
rocket = "0.5.0-rc.1"
serde = "^1.0.136"
serde_json = "^1.0.79"
serde_repr = "^0.1.7"
bitflags = "^1.3.2"
reqwest = { version = "^0.11.9", features = ["json", "multipart"] }
ring = "^0.16.20"
hex = "^0.4.3"
chrono = { version = "^0.4.19", features = ["serde"] }
thiserror = "^1.0.30"
common-multipart-rfc7578 = "^0.3.1"
bytes = "^1.1.0"
tokio-util = { version = "^0.7.0", features = ["io"] }
